### PR TITLE
Fix licensing problems and remove proprietary code

### PR DESCRIPTION
**Pull request by llunacb**
hi , jeff.

I noticed tht the repository still had some proprietary code laying around that I dont think is allowed to be there. I also noticed that there were some problems with the license that makes it impossible for friends to contribute through github. I have fixed both of those problems in this PR.

I think I ahve executed this task in the optimal manner but feel free to tell me if I have made any mistakes and I will correct them.

Thans,
luna!

### CODE REVIEW

**Review by ZaDarkSide — COMMENTED** [review]
Looks good to me 👍

**Comment by Yotsubal** [comment]
LGTM

**Comment by Yotsubal** [comment]
What a joke:
{3637CD12-4F0B-4906-9F2D-E2D00A56D7F2}

**Comment by AJPfleger** [comment]
Would it make sense to split this PR in 2? Maybe first doing a clean removal and then fixing the license?
I would not feel comfortable adding 60k new lines that fix a license (or "fix a license") hiding within 1kk changed lines.

**Comment by Architector4** [comment]
> Would it make sense to split this PR in 2? Maybe first doing a clean removal and then fixing the license? I would not feel comfortable adding 60k new lines that fix a license (or "fix a license") hiding within 1kk changed lines.

Sounds like a good plan. Just have to make sure the fixed code still includes linuxdoom, of course.

**Review by ewancg — COMMENTED** [review]
LGTM

**Comment by thecaralice** [comment]
Shouldn't have forked I guess, that's why your PR got closed /hj

**Comment by filippocastelli** [comment]
next time you want to contribute just open an issue and for every file type the diff in the comments. That's the way to do it in WCL.

**Pull request closed without merging**
