### PR TITLE
chore: delete source, replace with DOOM (1993)

### PR DESCRIPTION
**Pull request by RealMCoded**
the "no forking" rule is stupid, so i replaced the entire source code repo with the source code for DOOM (1993).

### CODE REVIEW

**Review by nofishonfriday — COMMENTED** [review]
LGTM

**Comment by RitzDx** [comment]
ok buddy

**Comment by ioletsgo** [comment]
looks good to me

**Comment by myslivets** [comment]
hyper-anime

**Comment by harris1111** [comment]
You can merge it now.

**Comment by phamanhquyet** [comment]
LGTM

**Comment by 0x5066** [comment]
LGTM

**Comment by fnc12** [comment]
LGTM kurwa!

**Comment by 3kh0** [comment]
Good contribution

**Comment by RealMCoded** [comment]
Cheers for the positivity everyone! Not sure why they closed this PR however... Probably a misclick 🤔

**Pull request closed without merging**
