### PR TITLE
Remove wac_browser.7z

### PR DESCRIPTION
**Pull request by pixeldesu**
The archive contains similar code as in `Src/Components/wac_browser` already, except that the code already present in the repository has the extra namespace and that the file `api__wac_browser.h` has an extra underscore compared to the one in the archive, thus the archive can be discarded. (and otherwise be retrieved from git history anyway)

### CODE REVIEW

**Comment by morsik** [comment]
Well, even removed it's still in repo history and will take that 25KB forever...

**Review by GitMensch — COMMENTED** [review]
Good catch. That's at least not referenced anywhere in the repository.

Did you also verify that building the wac_browser works from the repo and the result works fine with the Winamp build?

**Comment by pixeldesu** [comment]
@GitMensch I have not verified that yet. That said, I might revise this PR later to remove some more archives of singular folders that seem to be present across the repository (and are not dependency-related whatsoever)

**Comment by GitMensch** [comment]
Apart from this PR needing a proper rebase - which can be done - what is the reason to close this?
Did you find out, that the file is needed for the build system?

**Comment by pixeldesu** [comment]
@GitMensch I'll probably just do the PR anew considering there are more things to remove here, and I'll also wait until the repository vandalism went down a bit, there's too much traction on this repository for the maintainers to even work properly on anything.

**Pull request closed without merging**
