### PR TITLE
FREE AS IN LIBRE

### PR DESCRIPTION
**Pull request by NekoSam395**
Free and open-source software (FOSS) is software that is available under a license that grants the right to use, modify, and distribute the software, modified or not, to everyone free of charge. The public availability of the source code is, therefore, a necessary but not sufficient condition. FOSS is an inclusive umbrella term for free software and open-source software. FOSS is in contrast to proprietary software, where the software is under restrictive copyright or licensing and the source code is hidden from the users.

[By Wikipedia, the free encyclopedia.](https://en.wikipedia.org/wiki/Free_and_open-source_software) Text is available under the [Creative Commons Attribution-ShareAlike License 4.0](https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License); additional terms may apply.

### CODE REVIEW

**Comment by darkain** [comment]
`No Forking: You may not create, maintain, or distribute a forked version of the software.`

@NekoSam395 You've already violated the license just to make this PR. That's the level of bullshit that this license is. You technically are not even allowed to do ANYTHING with this code, not even have a local copy, due to the "no forking" license.

**Comment by NekoSam395** [comment]
fuck you, fuck your NFT thing, and FUCK THIS REPO IN PARTICULAR

**Comment by nofishonfriday** [comment]
It violates GitHub TOS:
> By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories '

https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users

**Comment by kbity** [comment]
it's technically "open source" but restrictive source code license is considered to be "source available". source code is about as free as a decomp's source code.

**Comment by darkain** [comment]
@kbity "open source" has an actual definition, and right in that definition before it even gets into the requirements it states `Providing access to the source code is not enough for software to be considered "open-source".` - this is NOT an open-source license. 

https://en.wikipedia.org/wiki/The_Open_Source_Definition

**Comment by NekoSam395** [comment]
@darkain 
# THEN, WHAT THE FUCK IS THE POINT OF RELEASES THE WHOLE CODE WITH ABILITY OF DOING FORK, PR, AND STUFFS!??!?!

**Comment by realeatham** [comment]
> Free and open-source software (FOSS) is software that is available under a license that grants the right to use, modify, and distribute the software, modified or not, to everyone free of charge. The public availability of the source code is, therefore, a necessary but not sufficient condition. FOSS is an inclusive umbrella term for free software and open-source software. FOSS is in contrast to proprietary software, where the software is under restrictive copyright or licensing and the source code is hidden from the users.

That would be FLOSS not Foss, as foss can only be available for a fee

**Comment by NekoSam395** [comment]
@realeatham yea but FLOSS term is deprecated, as 'Free' in 'FOSS' already covers both 'Libre' and 'Gratis'.

**Comment by realeatham** [comment]
Source? Because normally in this context free  specifically does not have to be gratis

**Comment by realeatham** [comment]
Never seen anyone say FOSS requires that

**Comment by NekoSam395** [comment]
finding FLOSS in Wikipedia redirects to that article btw

**Comment by realeatham** [comment]
That means nothing, there is also a suggestion to make free software and open software redirect there.

**Comment by realeatham** [comment]
Please provide an actual source

**Comment by realeatham** [comment]
Maybe from the fsf or OSI.

**Comment by NekoSam395** [comment]
1984

**Comment by MTFixGMD** [comment]
wait can i say faggot on here

**Comment by Programazing** [comment]
> `No Forking: You may not create, maintain, or distribute a forked version of the software.`
> 
> @NekoSam395 You've already violated the license just to make this PR. That's the level of bullshit that this license is. You technically are not even allowed to do ANYTHING with this code, not even have a local copy, due to the "no forking" license.

@darkain According to the license itself you can download it and modify it for private use, but not redistribute that modified copy.

@NekoSam395 if it bothers you that much, and the maintainer won't make it fully open source, study how the program works and make your own software based on the idea of the original.

**Comment by vukovinski** [comment]
What's the actual license?

**Review by Neals86 — COMMENTED** [review]
LGTM

**Pull request closed without merging**
